version: "3"
services:
  node-app:
    image: vikas1412/node-website:1.3
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOTUSERNAME=admin
      - MONGO_INITDB_ROOTPASSWORD=vikas
    volumes:
      - mongodb-volume:/data/db
  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=vikas
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: unless-stopped

volumes:
  mongodb-volume:
    driver: local